### PR TITLE
Project and project permissions

### PR DESCRIPTION
**Pull request by alxckn**
Project creation
Management of permissions to project within controller and twig
Update User
Update views and style

### CODE REVIEW

**Comment by JunkOSGitHub** [comment]
@Crymsius We merge on develop or master ?

**Comment by alxckn** [comment]
@JunkOSGitHub Last week's instructions were to push everything to develop

**Comment by Crymsius** [comment]
Theoretically on develop, but since nobody understood instructions and sent PR on master...

**Comment by JunkOSGitHub** [comment]
@Crymsius you will have to manually merge develop in master

**Pull request merged**
